version: '3.7'

services:
  queue:
    image: rabbitmq:4-management
    command: sh -c "echo [rabbitmq_management,rabbitmq_management_agent,rabbitmq_amqp1_0]. > /etc/rabbitmq/enabled_plugins && exec docker-entrypoint.sh rabbitmq-server"
    ports:
      - 127.0.0.1:5672:5672
      - 15672:15672
