version: '3.7'

services:
  activemq:
    image: symptoma/activemq:5.18.0
    ports:
      - 5672:5672
      - 8161:8161
    volumes:
      - ../activemq/jetty.xml:/opt/activemq/conf/jetty.xml
      - ../activemq/activemq.xml:/opt/activemq/conf/activemq.xml
