<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.7.511.8" />
    <PackageReference Include="AWSSDK.SecurityToken" Version="3.7.504.50" />
    <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\src\ArmoniK.Core.Common.csproj" />
  </ItemGroup>

</Project>
